# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0002_confprofile'),
        ('accounts', '0002_agent_tel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conf_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='vox.ConfProfile'),
        ),
    ]
