# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 09:25
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180521_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='settings',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
