# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agent_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Supervisor'), ('3', 'Crew')], default='3', max_length=1),
        ),
    ]
