# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20180629_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='conf_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='vox.ConfProfile'),
        ),
    ]
