# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0006_call_callactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='line',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='call',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Ringing'), (2, 'Dialing'), (3, 'Missed'), (4, 'Failed'), (5, 'In Call'), (6, 'Completed')], default=0),
        ),
    ]
