# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0007_auto_20180706_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('1', 'Outgoing'), ('2', 'Incoming')], default='1', max_length=1),
        ),
    ]
