# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0008_call_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('1', 'Incoming'), ('2', 'Outgoing')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Ringing'), (2, 'Dialing'), (3, 'Missed'), (4, 'Failed'), (5, 'In Call'), (9, 'Completed')], default=0),
        ),
    ]
