# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0010_auto_20180706_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-start']},
        ),
    ]
