# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_profiles', to='vox.TelSwitch')),
            ],
        ),
    ]
