# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0002_confprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telprofile',
            old_name='extension',
            new_name='extn',
        ),
        migrations.AddField(
            model_name='telprofile',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
