# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_suitecrm_auth_expires'),
        ('vox', '0005_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hub.Channel'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mapped_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
