# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0006_auto_20180627_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
