# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0007_auto_20180627_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mapped_id',
            new_name='source_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='source_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
