# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('1', 'Suite CRM'), ('2', 'Vtiger'), ('3', 'Salesforce'), ('4', 'Freshdesk')], default='1', max_length=2)),
                ('category', models.CharField(choices=[('1', 'CRM'), ('2', 'Support')], default='1', max_length=2)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugerCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('auth_response', jsonfield.fields.JSONField()),
            ],
        ),
    ]
