# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('auth_response', jsonfield.fields.JSONField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suitecrm', to='hub.Channel')),
            ],
            options={
                'db_table': 'hub_suitecrm',
            },
        ),
        migrations.DeleteModel(
            name='SugerCrm',
        ),
    ]
