# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20180627_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitecrm',
            name='address',
            field=models.URLField(default='139.162.57.32'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suitecrm',
            name='auth_response',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
