# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20180627_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitecrm',
            name='address',
        ),
        migrations.AddField(
            model_name='channel',
            name='address',
            field=models.URLField(default='http://139.162.57.32'),
            preserve_default=False,
        ),
    ]
