# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20180627_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitecrm',
            name='auth_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
